site_name: eru
site_url: https://fllay.github.io
site_author: you
site_description: a short description of your website

nav:
  - About: index.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml